services:
  user-service-db:
    image: postgres:16-alpine
    container_name: user-service-db
    environment:
      POSTGRES_DB: user_service_db
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - dns-network
  
  product-service-db:
    image: postgres:16-alpine
    container_name: product-service-db
    environment:
      POSTGRES_DB: product_service_db
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    networks:
      - dns-network

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8080:8080"
    environment:
      SPRING_R2DBC_URL: r2dbc:postgresql://user-service-db:5432/user_service_db
      SPRING_R2DBC_USERNAME: postgres
      SPRING_R2DBC_PASSWORD: postgres
      
      SPRING_LIQUIBASE_URL: jdbc:postgresql://user-service-db:5432/user_service_db
      SPRING_LIQUIBASE_USER: postgres
      SPRING_LIQUIBASE_PASSWORD: postgres  
    depends_on:
      - user-service-db
    networks:
      - dns-network
      
  product-service:
    build: ./product-service
    container_name: product-service
    ports:
      - "8082:8082"
    environment:
      SPRING_R2DBC_URL: r2dbc:postgresql://product-service-db:5432/product_service_db
      SPRING_R2DBC_USERNAME: postgres
      SPRING_R2DBC_PASSWORD: postgres
      
      SPRING_LIQUIBASE_URL: jdbc:postgresql://product-service-db:5432/product_service_db
      SPRING_LIQUIBASE_USER: postgres
      SPRING_LIQUIBASE_PASSWORD: postgres  
    depends_on:
      - product-service-db
    networks:
      - dns-network    

networks:
  dns-network:
    driver: bridge
