FROM eclipse-temurin:21-jdk-alpine AS build
WORKDIR /app

COPY . .

RUN ./gradlew :order-service:build -x test --no-daemon

FROM eclipse-temurin:21-jre-alpine
WORKDIR /app

COPY --from=build /app/order-service/build/libs/*.jar app.jar

ENTRYPOINT ["java", "-jar", "app.jar"]

