spring:
  application:
    name: product-service
  reactor:
    context-propagation: auto
  r2dbc:
    url: r2dbc:postgresql://localhost:5433/product_service_db
    username: postgres
    password: postgres

  messages:
    encoding: UTF-8

  liquibase:
    url: jdbc:postgresql://localhost:5433/product_service_db
    user: postgres
    password: postgres
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8082

logging:
  level:
    org.springframework.r2dbc: DEBUG
    org.springframework.cloud.gateway: TRACE
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}] %m%n"

management:
    sampling:
      probability: 1.0 # Логируем каждый запрос

